spring:
  datasource:
    test1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mysql-test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      hikari:
      minimum-idle: 20 # 池中维护的最小空闲连接数，默认为 10 个。
      maximum-pool-size: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
    test2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mysql_test2?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      hikari:
      minimum-idle: 20 # 池中维护的最小空闲连接数，默认为 10 个。
      maximum-pool-size: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。